steps:
  - id: install_packages
    name: 'gcr.io/cloud-builders/npm'
    args:
      - 'install'

  - id: build_files
    name: 'gcr.io/cloud-builders/npm'
    args:
      - 'run'
      - 'build-gcp'
    waitFor:
      - install_packages

  - name: 'gcr.io/cloud-builders/gsutil'
    id: copy_files
    dir: /workspace
    args: ['cp','-r','dist/*', 'ipla-1652-embark-dev']
    waitFor:
      - build_files

  - name: 'gcr.io/cloud-builders/gsutil'
    id: set_website_configuration
    args: ['web', 'set', '-m', 'index.html','ipla-1652-embark-dev']
    waitFor:
      - copy_files

  - name: 'gcr.io/cloud-builders/gsutil'
    id: set_permissions_for_website_files
    args: ['acl','ch','-u','AllUsers:R','-r', 'ipla-1652-embark-dev']
    waitFor:
      - set_website_configuration
